name: "go2rtc"
description: "Ultimate camera streaming application with support for RTSP, RTMP, HTTP-FLV, WebRTC, MSE, HLS, MP4, MJPEG, HomeKit, FFmpeg, etc."
version: "1.9.9"
slug: "go2rtc"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
init: false
startup: services
stage: stable

url: "https://github.com/pk802/go2rtc"

# Use your custom Docker image
image: "ghcr.io/pk802/go2rtc:latest"

map:
  - "config:rw"
  - "ssl:ro"
  - "media:rw"
  - "backup:rw"

ports:
  "1984/tcp": 1984
  "8554/tcp": 8554
  "8555/tcp": 8555

ports_description:
  "1984/tcp": "Web UI and API"
  "8554/tcp": "RTSP TCP server"
  "8555/tcp": "RTSP UDP server"

options:
  log_level: "info"
  streams: {}

schema:
  log_level: "list(trace|debug|info|warn|error|fatal|panic)?"
  streams: "dict?"

host_network: true
video: true
audio: true
homeassistant_api: true

ingress: true
ingress_port: 1984
panel_icon: mdi:camera-wireless

backup: include